---
title: "Bayesian Inference"
---

Bayesian inference is an alternative to inferring model fits from data.
With maximum likelihood we have worked off the assumption that there is a true known value for the parameters and that the data varies.
That is, we are interested with $p(D|\theta$).
In direct contrast, for Bayesian inference we have that the data is known and we are interested in the probability distribution of the parameters, $p(\theta|D)$.
This is a subtle yet important point that has led to constant confusion and arguments.
The two points of view are also related through Bayes' Theorem.

::: {.callout title="Bayes' Theorem"}
$$
p(A|B) = \frac{p(A,B)}{p(B)}
$$
:::


### Conjugate Priors
Numerical methods for sampling from complicated distributions are a relatively modern advancement.
Therefore, Bayesian's typically focused on trying to get closed-form solutions to posterior distributions.
This was done through the use of Conjugate Priors.

Their use today is still important, as conjugate priors can be placed on certain parameters to improve computational efficiency.

### Bayes' Estimators
When we were investigating maximum likelihood, we obtained a point estimate for the parameters.
In a similar fashion we can obtain point estimates of parameters in Bayesian Inference.
These estimates minimise a loss function.

The maximum posterior estimate, whilst being an arguably obvious choice, is not always a Bayes' estimator.
Does this mean you should not use the maximum posterior as a point estimate?
I am always keen for a good argument but I do not know if this one can be answered easily.
You can view maximum posterior estimates as a maximum likelihood method with regularization, in which case they are valid but not Bayesian.
Another criticism I would like to highlight is that the posterior distribution, in general, is not invariant undertransformation.
Consider Binomial data such that the number of trials is 10 and the number of successes is 3.
We have,
$$
p(\theta|D) \propto \theta^3(1-\theta)^7 \theta^{\alpha-1}(1-\theta)^{\beta-1},
$$
where we have assumed a Beta distribution prior with hyperparameters $\alpha$ and $\beta$ and $p$ is the probability of success.
The resulting posterior (as beta distributions are conjugate to binomial distributions) is again a Beta distribution,
$$
p(\theta|D) \propto \theta^{2 + \alpha}(1-\theta)^{6 + \beta},
$$
which is maximised at,
$$
\hat{\theta} = {\frac {1 + \alpha}{6 + \alpha +\beta}},
$$
for $\alpha>0$ and $\beta >0$. This would be our maximum posterior estimate once we decide on the value of our hyperparameters.

An alternative, yet equally valid parameterisation, is to use log-odds ratio instead of probability in the binomial distribution.
By taking our posterior and defining the transformation $\phi = \log \theta - \log(1-\theta)$, our posterior can be expressed as,

